inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  NewCops: enable

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false
